title: BanglaWiki
description: BanglaWiki project.

exclude:
  - bin
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - docs
  - Gemfile*
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script
  - test
  - vendor

permalink: "/:path/"

collections:
  articles:
    output: true
    permalink: "/:path/"

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/cards/default.png
  - scope:
      path: ""
      type: articles
    values:
      layout: article

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css/
  style: compressed
  load_paths:
    - node_modules

logo: /assets/images/cards/default.png

github:
  repository_nwo: banglawiki/banglawik.github.io

twitter:
  username: banglawiki

facebook:
  publisher: https://www.facebook.com/banglawiki/